### ISSUE TITLE
Rydd opp i environment-urls

### ISSUE THREAD

**Issue by PerOlavM** [navikt/decorator-next#175]
VITE_MIN_SIDE_URL må defineres
+ gjennomgå alle URL-er i .env

**Comment by max-nav** [comment]
Alle client environment variabler kommer fra serveren nå. Du kan teste ved å gjøre window.__DECORATOR_DATA__
<img width="723" alt="image" src="https://github.com/navikt/decorator-next/assets/135981901/763f0b15-8e04-4f86-8103-9be9b6b1ef01">
