### ISSUE TITLE
Avvikle urlLookupTable

### ISSUE THREAD

**Issue by max-nav** [navikt/decorator-next#188]

**Comment by max-nav** [comment]
@anders-nom Trenger vell kanskje ikke foreta oss så mye her? Så ikke at den hadde noe funksjon i dagens-dekoratør

**Comment by anders-nom** [comment]
Den har minimal funksjonalitet i dag ja. Kan brukes til å erstatte prod-url'er i dev-miljøet, men løsningen krever noe vedlikehold som ikke har blitt gjort på noen år. Dessuten er den disabled by default nå, og tror "ingen" har enablet den. 😅

**Comment by max-nav** [comment]
Den er god! Da prøver vi uten nå :D
