### ISSUE TITLE
Mangelfull skjermleserstøtte for søkeresultater

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/decorator-next#212]
Feil meldt inn av UU-teamet. Pilnavigasjon slutter å virke ved 2. gangs forsøk:

Kari Anne Reitan Andersen skriver (videresendt fra innmelder):

- ~~Første gangen du søker og får opp forhåndstreffene, kan du pile rett ned i lista og velge.~~
- ~~Når du trykker Escape og deretter åpner søket igjen og får opp forhåndstreff, så fungerer ikke pil ned i lista lenger.~~
- Han har testet både i Chrome og i Edge.
- Han skriver også at han får heller ingen beskjed med skjermleser at treffene faktisk vises.

**Comment by terjeofnorway** [comment]
Denne ble opprinnelig rapportert på gamle dekoratøren. Når vi etterhvert går over til den nye foreslår jeg at vi ber UU-teamet gjøre en ny test slik at vi ikke feilsøker noe som ikke lenger er relevant. Jeg legger den i teknisk backlog så lenge.

**Comment by anders-nom** [comment]
Tror denne skal være fikset i ny dekoratør
