### ISSUE TITLE
Sticky-header

### ISSUE THREAD

**Issue by anders-nom** [navikt/decorator-next#216]
Reimplementere sticky-header, eller droppe den? Har vi målinger på bruk av dagens sticky header?

**Comment by andnorda** [comment]
Planen er å fjerne sticky-funksjonalitet for den første release, og ta det opp som tema igjen på et senere tidspunkt. Det er ikke sikkert det er ønskelig å videreføre sticky-funksjonalitet, og den implementasjonen vi har nå er uansett broken.
