### ISSUE TITLE
Bug i Salesforce Experience

### ISSUE THREAD

**Issue by mamikals** [navikt/decorator-next#246]
Link til URL hvor feilen oppstår:
https://navdialog--sit2.sandbox.my.site.com/Innboks/s/ og andre Salesforce instanser

Kort forklaring
Salesforce henter og laster inn dekoratøren fra https://dekoratoren.ekstern.dev.nav.no/. Før så var dev URLene whitelistet for dette, så vi kunne teste og bruke den i dev, se https://github.com/navikt/nav-dekoratoren/blob/master/src/server/server.ts#L44. Dette har sluttet å funke i den nye versjonen av dekoratøren, fordi feltet Access-Control-Allow-Origin ikke er inkludert i responsen 😄

**Comment by anders-nom** [comment]
Denne skal være fikset nå.
