### ISSUE TITLE
Bug i hm-soknad

### ISSUE THREAD

**Issue by olesls** [navikt/decorator-next#250]
Link til URL hvor feilen oppstår: https://hjelpemidler-prod-mirror.ekstern.dev.nav.no/hjelpemidler/digitalsoknadhjelpemidler/

Repo: https://github.com/navikt/hm-soknad

Kort forklaring: Får feil i konsollen
```
Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at new Yn (language-selector.ts:81:24)
    at language-selector.ts:109:16
```
som ser ut til å ha dukket opp etter siste release https://github.com/navikt/nav-dekoratoren/releases/tag/v1.56.0

Oppdaget det ved at alle Cypress-testene våre startet å feile 14. mars 2024 (https://github.com/navikt/hm-soknad/actions/runs/8293464419/job/22700181660)

**Comment by anders-nom** [comment]
Denne var forårsaket av en deployet feature-branch, skal ikke være et problem med nåværende main.
