### ISSUE TITLE
Logge pageviews ved back/forward navigering

### ISSUE THREAD

**Issue by anders-nom** [navikt/decorator-next#258]

**Comment by anders-nom** [comment]
Skal vi logge dette som vanlige pageviews, eller noe annet? (Venter på tilbakemeldinger)

**Comment by PerOlavM** [comment]
Løsning med å logge popstate-eventet gir ikke så mye merverdi.
Vil bare gi logging av router-state fra aktuell  app på den siden som det utføres et back eller forward i.
Vil også trigges ved hopp til ankerlenker.

Må løses med å lytte til history push og pop og gjøre kvalifisert logging basert på historikken. Utsettes

**Comment by anders-nom** [comment]
Tenker vi klarer oss uten dette, kan heller ta opp igjen dersom noen etterspør. Vi hadde det ikke i den gamle dekoratøren heller.
