### ISSUE TITLE
"Logg ut"-knapp mangler for arbeidsgiver

### ISSUE THREAD

**Issue by andnorda** [navikt/decorator-next#260]
https://nav-it.slack.com/archives/C05RW7DTMK3/p1714131315458229?thread_ts=1714123500.822439&cid=C05RW7DTMK3

**Comment by anders-nom** [comment]
Løsningen her blir at vi lager en innlogget meny også for arbeidsgiver, som har logg ut lenke slik som privatperson-menyen:
https://www.figma.com/design/CoEsuEKBLAxC2vnSrjwWcy/Meny-og-navigasjon?node-id=389-1114&t=CACGooE57FfKqSig-0
