### ISSUE TITLE
Utloggingsvarsel fungerer ikke korrekt

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/decorator-next#292]
# logoutDebug lar seg ikke trigge via console slik som i gamle dekoratøren.

Kan testes i samisk samtalebestilling:
https://www.nav.no/person/bestilling-av-samisk-samtale

I console, skriv:
window.loginDebug.expireToken(60)

Dette burde ha trigget utloggingsvarsel.

# ved visning av utloggingsvarsel vises kun 'undefined' (se screenshot)
Dette skjer dersom man faktisk venter i 55 minutter etter innlogging og lar varselet dukke opp av seg selv (dvs uten å trigge).

![image](https://github.com/navikt/decorator-next/assets/1443997/45d78edc-c323-48eb-a171-8d1dba5c73e4)

**Comment by terjeofnorway** [comment]
Jeg kan kikke på denne, men det blir ikke en høy prioritet nå som to av utviklerne er på ferie de neste par ukene.

**Comment by anders-nom** [comment]
Skal være fikset!
