### ISSUE TITLE
Problemer med module.css når dekoratøren kjører sammen med frontenden?

### ISSUE THREAD

**Issue by PerOlavM** [navikt/decorator-next#297]
Dekoratøren alene:
![Image](https://github.com/navikt/decorator-next/assets/35491554/5bddd3b5-fcff-4b8b-bf12-031a1fde874f)

Dekoratøren sammen med frontenden:

![Image](https://github.com/navikt/decorator-next/assets/35491554/23a9f1d8-0f9f-4d02-88be-5103f98138f6)

**Comment by anders-nom** [comment]
Skal være fikset.
