### ISSUE TITLE
Headeren forsvinner opp i Safari ved bruk av magic trackpad

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/decorator-next#303]
Antar at denne bare kan gjenskapes på Mac:

1. Åpne nav.no i Safari
2. Bruk trackpad på selve laptopen eller magic trackpad for å scrolle siden litt nedover (med 2-finger scroll gesture)
3. Scroll deretter opp til toppen med et par raske swipes  som du ville gjort om du ønsket å scrolle raskt til toppen av siden.
4. Headeren har nå flyttet seg ovenfor skjermkanten og vises bare dersom man scroller litt ned og deretter opp igjen.

Ser ut til å kun gjelde Safari. Jeg har ikke greid å gjenskape i Chrome, Firefox eller Edge

**Comment by anders-nom** [comment]
Burde være fikset i ny versjon av sticky-headeren.
